# Netlify Configuration for TextToReels.in
# Optimized for performance and SEO

[build]
  publish = "."
  command = "echo 'Static site deployment ready'"

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' fonts.googleapis.com fonts.gstatic.com; font-src fonts.googleapis.com fonts.gstatic.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' cloud.umami.is www.googletagmanager.com www.google-analytics.com www.clarity.ms; img-src 'self' data: www.google-analytics.com www.googletagmanager.com; connect-src 'self' cloud.umami.is www.google-analytics.com www.googletagmanager.com www.clarity.ms analytics.google.com; frame-src 'none';"

# Cache static assets (1 year)
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML content (1 hour)
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Content pages caching
[[headers]]
  for = "/content/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Redirects for SEO-friendly URLs
[[redirects]]
  from = "/privacy"
  to = "/privacy-policy.html"
  status = 301

[[redirects]]
  from = "/terms"
  to = "/terms-of-service.html"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 301

[[redirects]]
  from = "/api"
  to = "/api.html"
  status = 301

[[redirects]]
  from = "/docs"
  to = "/api.html"
  status = 301

# Redirect old content URLs to proper content-types structure
[[redirects]]
  from = "/content/love-quotes-hindi*"
  to = "/content-types/love-quotes/"
  status = 301

[[redirects]]
  from = "/content/*love-quotes*"
  to = "/content-types/love-quotes/"
  status = 301

[[redirects]]
  from = "/content/*motivational*"
  to = "/content-types/motivational-quotes/"
  status = 301

[[redirects]]
  from = "/content/*friendship*"
  to = "/content-types/friendship-quotes/"
  status = 301

[[redirects]]
  from = "/content/*birthday*"
  to = "/content-types/birthday-wishes/"
  status = 301

[[redirects]]
  from = "/content/*hindi-shayari*"
  to = "/content-types/hindi-shayari/"
  status = 301

[[redirects]]
  from = "/content/*good-morning*"
  to = "/content-types/good-morning/"
  status = 301

# Content directory handling
[[redirects]]
  from = "/content/:slug"
  to = "/content/:slug.html"
  status = 200
  conditions = {Path = "/content/:slug.html"}

# Fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Path = "!/**/*.html"}

# 404 handling
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404